mimir:
  image: nice/mimir
  links:
    - stardog
    - elastic
    - schema
  volumes_from:
    - stardog
  volumes:
    - bin/compiler:/compiler
    - .:/nunit
    - tests/compiler.IntegrationTests:/tests
  command: sleep 1000000
schema:
  image: nice/ontologies
  expose:
    - 80
  ports:
    - "20002:80"
stardog:
  image: nice/ld-docker-stardog
  ports:
    - "5820:5820"
  volumes:
    - /dev/urandom:/dev/random
elastic:
  image: nice/ld-docker-elasticsearch
  ports:
    - "9200:9200"