mimir:
  image: nice/mimir
  links:
    - stardog
    - elastic
  volumes_from:
    - stardog
  volumes:
    - bin/compiler:/compiler
    - samples:/samples
    - artifacts:/artifacts
    - .:/nunit
    - tests/compiler.IntegrationTests:/tests
  command: sleep 1000000
stardog:
  image: nice/ld-docker-stardog
  ports:
    - "5820:5820"
  volumes:
    - /dev/urandom:/dev/random
elastic:
  image: nice/ld-docker-elasticsearch
  ports:
    - "9200:9200"