compiler:
  image: "${IMAGE_NAME}:${IMAGE_VERSION}"
  volumes_from:
    - stardog
  ports:
    - "8081:8081"
  labels:
    io.rancher.sidekicks: stardog
  external_links:
    - elasticsearch/elastic:elastic
    - ontologies/schema:schema
    - resourceapi/resourceapi:resourceapi
stardog:
  image: nice/ld-docker-stardog
  ports:
    - "5820:5820"
  volumes:
    - /dev/urandom:/dev/random