compiler:
  image: nice/ld-compiler
  links:
    - stardog
    - elastic
    - schema
  volumes_from:
    - stardog
  volumes:
    - /artifacts:/artifacts
  ports:
    - "8083:8083"
schema:
  image: nice/ontologies
  expose:
    - 80
  ports:
    - "20002:80"
stardog:
  image: nice/ld-docker-stardog
  ports:
    - "5820:5820"
  volumes:
    - /dev/urandom:/dev/random
elastic:
  image: nice/ld-docker-elasticsearch
  ports:
    - "9200:9200"
integrationtests:
  image: nice/ld-publisher-base
  links:
    - compiler
    - elastic
  volumes:
    - .:/compiler-src
    - /artifacts:/artifacts
  command: sleep 10000000